export const ROUTE = {
  base: "/",
  home: "/",
  catalog: "/catalog",
  signIn: "/sign-in",
  signUp: "/sign-up",
  basket: "/basket",
  about: "/about",
  contacts: "/contacts",
  order: "/order",
  profile: "/profile",
  admin: "/admin",
  addNews: "/admin/addNews",
  addProducts: "/admin/addProducts",
  addShares: "/admin/addShares",
  allNews: "/admin/allNews",
  allProducts: "/admin/allProducts",
  allShares: "/admin/allShares",
  applications: "/admin/applications"
};
