export const ROUTE = {
  base: "/",
  home: "/",
  catalog: "/catalog",
  signIn: "/sign-in",
  signUp: "/sign-up",
  basket: "/basket",
  // about: "/about",
  // contacts: "/contacts",
  order: "/order",
  profile: "/profile",
  admin: "/admin",
  addProducts: "/admin/add-products",
  addNews: "/admin/add-news",
  allProducts: "/admin/all-products",
  applications: "/admin/applications",
  archive: "/admin/product/archive/",
  users: "/admin/users/",
  createColor: "/admin/color/",
  createBrand: "/admin/brand",
  createCategory: "/admin/category/",
};
